title: Melody Mates
description: "Music Matching Social Media Website"
owner_name: Hannah, Rowan, Carson, Gaheera, Brandon, Rhea
github_username: gaheerb
github_repo: "sprint4_backend" 
baseurl: "/sprint4_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/ai.md
  - navigation/melodymates/home.md
  - navigation/about_us/home.md
